# Etapa 1: Build
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Copiar el archivo .csproj y restaurar dependencias
COPY *.csproj ./
RUN dotnet restore

# Copiar todo el código del proyecto y compilar
COPY . ./
RUN dotnet publish -c Release -o /app/publish

# Etapa 2: Runtime
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
COPY --from=build /app/publish .

# Exponer los puertos para HTTP y HTTPS
EXPOSE 80
EXPOSE 443

# Definir el comando para correr la aplicación
ENTRYPOINT ["dotnet", "Sistema_Facturacion.dll"]
